#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

@author: Salva
"""
"""
Nombre del grupo: "Comillas Dobles"
Participantes:
- Durand, Salvador
- Mateos, Martin
"""


import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
from scipy.signal import find_peaks
from IPython import get_ipython
import pandas as pd
import sklearn as sck
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, StratifiedGroupKFold
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

df_datos = pd.read_csv('C:/Users/ADMIN/Downloads/salvaTP02//kuzushiji_full.csv')

df_etiqueta = pd.read_csv('C:/Users/ADMIN/Downloads/salvaTP02//kmnist_classmap_char.csv')


print(len(df_datos))

print(len(df_datos.columns))

print(len(df_etiqueta))

primero = df_datos.iloc[55,[i for i in range (784)]]

primero = np.array(primero).reshape((28,28))

plt.imshow(primero, cmap = 'gray')
plt.title("Imagen 56")
plt.show

#%%

conteo_clases = df_datos['label'].value_counts()

# Creo el gráfico de barras
plt.bar(conteo_clases.index, conteo_clases.values)
plt.title("Cantidad de ejemplos por clase")
plt.xlabel("Clase")
plt.ylabel("Cantidad de imágenes")
plt.xticks(range(10))
plt.show()


#%% Represenacion por promedio
x= df_datos.drop('label', axis = 1).values
y = df_datos['label'].values

plt.title('Promedio del pixel utilizado en cada clase')
plt.axis('off')

for i in range(10):
    mean_img = x[y == i].mean(axis = 0).reshape(28,28)
    plt.subplot(2, 5, i+1)
    plt.imshow(mean_img, cmap = 'plasma')
    plt.title(f'clase{i}')
    plt.axis('off')
    
plt.tight_layout()
plt.show()

#%% Representacion por medianas

x= df_datos.drop('label', axis = 1).values
y = df_datos['label'].values

plt.title('Valor mediano del pixel utilizado en cada clase')
plt.axis('off')


for i in range(10):
    median_img = np.median(x[y == i], axis = 0).reshape(28,28)
    plt.subplot(2, 5, i+1)
    plt.imshow(median_img, cmap = 'plasma')
    plt.title(f'clase{i}')
    plt.axis('off')
    
plt.tight_layout()
plt.show()

#%% Represetación por valor de varianza

x= df_datos.drop('label', axis = 1).values
y = df_datos['label'].values

plt.title('Varianza de los pixeles utilizados en cada clase')
plt.axis('off')


for i in range(10):
    median_img = np.var(x[y == i], axis = 0).reshape(28,28)
    plt.subplot(2, 5, i+1)
    plt.imshow(median_img, cmap = 'plasma')
    plt.title(f'clase{i}')
    plt.axis('off')
    
plt.tight_layout()
plt.show()

#%% Clasificacion binaria - preparacion de los dataframe


df_1 = df_datos[y == 1]
df_2 = df_datos [y == 2]
df_3 = df_datos [y == 3]
df_4 = df_datos[y == 4 ]
df_5 = df_datos[y == 5]
df_6 = df_datos[y == 6]


df_1y2 =pd.concat([df_1, df_2])
df_1y3 =pd.concat([df_1, df_3])
df_3y6 = pd.concat([df_3, df_6])
df_2y6 = pd.concat([df_2,df_6])
df_4y5 = pd.concat ([df_4, df_5])


#%% PCA de clases 4 y 5

x= df_4y5.drop('label', axis = 1).values
y = df_4y5['label'].values
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
plt.figure(figsize = (8,6))
sb.scatterplot(x = x_pca[:, 0], y = x_pca [:, 1], hue=y, palette = 'tab10', s=10)
plt.title('proyeccion PCA de los caracteres')
plt.show()


#%% PCA de clases 2 y 6

x = df_2y6.drop('label', axis = 1).values
y = df_2y6['label'].values
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
plt.figure(figsize = (8,6))
sb.scatterplot(x = x_pca[:, 0], y = x_pca [:, 1], hue=y, palette = 'tab10', s=10)
plt.title('proyeccion PCA de los caracteres de clase 2 y 6')
plt.show()

#%% PCA de clases 2 y 1

x = df_1y2.drop('label', axis = 1).values
y = df_1y2['label'].values
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
plt.figure(figsize = (8,6))
sb.scatterplot(x = x_pca[:, 0], y = x_pca [:, 1], hue=y, palette = 'tab10', s=10)
plt.title('proyeccion PCA de los caracteres de clase 1 y 2')
plt.show()

#%% PCA entre clases 1 y 3

x = df_1y3.drop('label', axis = 1).values
y = df_1y3['label'].values
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
plt.figure(figsize = (8,6))
sb.scatterplot(x = x_pca[:, 0], y = x_pca [:, 1], hue=y, palette = 'tab10', s=10)
plt.title('proyeccion PCA de los caracteres de clase 1 y 3')
plt.show()
#%% PCA entre clases 3 y 6

x = df_3y6.drop('label', axis = 1).values
y = df_3y6['label'].values
pca = PCA(n_components=2)
x_pca = pca.fit_transform(x)
plt.figure(figsize = (8,6))
sb.scatterplot(x = x_pca[:, 0], y = x_pca [:, 1], hue=y, palette = 'tab10', s=10)
plt.title('proyeccion PCA de los caracteres de clase 3 y 6')
plt.show()

mask = (y == 4) | (y==5)
x_sub = x[mask]
y_sub = y [mask]

x_train, x_test, y_train, y_test = train_test_split(x_sub, y_sub, test_size = 0.30, random_state =42, stratify = y_sub)

k = 700
selector = SelectKBest(score_func= f_classif, k=k)
x_train_sel = selector.fit_transform(x_train, y_train)
x_test_sel = selector.transform(x_test)

#%% Algoritmo knn con los datos de test y train

k_neigbors = 3
knn = KNeighborsClassifier(n_neighbors = k_neigbors)
knn.fit(x_train_sel, y_train)

y_pred = knn.predict(x_test_sel)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, pos_label = 5)
rec = recall_score(y_test, y_pred, pos_label = 5)
f1 = f1_score(y_test, y_pred, pos_label = 5)

print(f"Accuracy: {acc: 6f}")
print(f"Precision: {prec: 6f}")
print(f"Recall: {rec: 6f}")
print(f"F1-score: {f1: 6f}")

print("otra forma")
print(classification_report(y_test, y_pred))

print(f"Cantidad de datos usados: {k} ")
print(f"Cantidad de vecinos usados: {k_neigbors}")

#%% matriz de confusion 700 pixeles y 3 vecinos
cm = confusion_matrix(y_test, y_pred, labels=[4, 5])

plt.figure(figsize=(5,4))
sb.heatmap(cm, annot=True, fmt='d', cmap='Blues',
           xticklabels=[4, 5], yticklabels=[4, 5])
plt.xlabel('Predicción')
plt.ylabel('Valor real')
plt.title('Matriz de confusión para 700 atributos (clases 4 y 5)')
plt.show()

#%% Comparacion de modelos KNN - Gráficas de las métricas

k_vecinos = [3, 5, 7, 9, 11]
pixeles = [3, 10, 100, 300, 500, 700, 784]
resultados = []

for p in pixeles:
    selector = SelectKBest(f_classif, k=p)
    x_train_sel = selector.fit_transform(x_train, y_train)
    x_test_sel = selector.transform(x_test)
    for k in k_vecinos:
        modelo = KNeighborsClassifier(n_neighbors=k)
        modelo.fit(x_train_sel, y_train)
        y_pred = modelo.predict(x_test_sel)
        
        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred, average='macro')
        rec = recall_score(y_test, y_pred, average='macro')
        
        resultados.append((p, k, acc, prec, rec))

df_resultados = pd.DataFrame(resultados, columns=['Pixeles', 'Vecinos', 'Accuracy', 'Precision', 'Recall'])

top3 = df_resultados.nlargest(3, 'Accuracy')
print(top3)

def rendimientoKNN(metrica:str):
    plt.figure(figsize=(10,6))
    for k in k_vecinos:
        subset = df_resultados[df_resultados['Vecinos'] == k]
        plt.plot(subset['Pixeles'], subset[metrica], marker='o', label=f'k={k}')

    plt.xlabel('Cantidad de atributos seleccionados')
    plt.ylabel(metrica)
    plt.title(f'{metrica} según cantidad de atributos y vecinos')
    plt.legend()
    plt.grid(True)
    plt.show()


rendimientoKNN('Accuracy')
rendimientoKNN('Precision')
rendimientoKNN('Recall')

#%% Entrenamiento del modelo con los resultados top3
#Tomamos todos los pixeles y 3 vecinos

modelo = KNeighborsClassifier(n_neighbors=3)
modelo.fit(x_train, y_train)
y_pred = modelo.predict(x_test)

#%% Matriz de confusión para el modelo entrenado
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 5))
sb.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[4, 5], yticklabels=[4, 5])
plt.xlabel('Predicción')
plt.ylabel('Valor real')
plt.title('Matriz de confusión')
plt.show()

print("Datos de desarrollo: ", x_dev.shape)
print("Datos de validacion (held out):", x_held.shape)
print("Datos de etiquetas de desarrollo: ", y_dev.shape)
print("Datos de etiquetas de validación (held out): ", y_held.shape)

#%% Prueba de las distintas profundidades

depths = [i for i in range(1,9, 2)] + [10] # 1, 3, 5, 7 para acortar el tiempo de ejecucion.


mean_scores = []

for d in depths:
    tree = DecisionTreeClassifier(max_depth = d, random_state= 42, criterion='entropy')
    scores = cross_val_score(tree,x_dev, y_dev, cv=4, scoring = 'accuracy') # cv=5 -> cv=4
    mean_scores.append(np.mean(scores))


print(f"Profundidad = {d}, accuracy promedio = {np.mean(scores):.4f}")
best_depth = depths[np.argmax(mean_scores)]
print(f"\n Mejor profundidad seleccionada: {best_depth}")

#%% Seleccionamos la mejor profundidad y lo entrenamos

best_tree = DecisionTreeClassifier(max_depth= best_depth, random_state= 42)
best_tree.fit(x_dev, y_dev)

#%% comparación de rendimiento x max profundidad

plt.figure(figsize=(8,5))
plt.plot(depths, mean_scores, marker='o', linestyle='-', color='blue')
plt.title('Exactitud promedio vs profundidad del árbol')
plt.xlabel('Profundidad máxima (10)')
plt.ylabel('Exactitud promedio (accuracy)')
plt.xticks(depths)
plt.grid(True)
plt.show()

# Mejor arbol
y_pred = best_tree.predict(x_held)

#%% Visualizamos metricas

print("\n reporte de Clasificacion: ")
print(classification_report(y_held, y_pred))
cm = confusion_matrix(y_held, y_pred)

#imagen de la matriz
plt.figure(figsize=(6, 5))
sb.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicción')
plt.ylabel('Valor real')
plt.title('Matriz de confusión')
plt.show()

#%% Cross validation para comparar

tree = DecisionTreeClassifier(random_state=42)

param_grid = {
    'max_depth' : depths, 
    'min_samples_split' : [2,5,10], 
    'min_samples_leaf' : [2], 
    'criterion' : ['gini', 'entropy'] }

cv = StratifiedKFold(n_splits= 4, shuffle= True, random_state=42)

grid_search = GridSearchCV(
    estimator = tree, 
    param_grid = param_grid, 
    cv=cv, 
    scoring = 'accuracy', 
    n_jobs = -1, 
    verbose = 1)

grid_search.fit(x_dev, y_dev)

#Guardo los resultados de los árboles
resultados = pd.DataFrame(grid_search.cv_results_)

print("Mejores parametros encontrados")
print(grid_search.best_params_)
print(f"Mejor exactitud promedio en validacion: {grid_search.best_score_:.3f}")

# Mejores parametros encontrados
# {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5}
# Mejor exactitud promedio en validacion: 0.716

#%% Predicciones
# Busco el mejor el arbol
mejor_arbol = grid_search.best_estimator_

# Visualizar el arbol
plt.figure(figsize=(25, 12))
plot_tree(mejor_arbol, filled=True, max_depth=3, fontsize=8)
plt.title("Árbol de Decisión con profundidad parcial 3 (Máxima profunidad = 10)")
plt.show()

# Lo entreno
mejor_arbol.fit(x_dev, y_dev)

# Predicciones
y_pred_held = mejor_arbol.predict(x_held)

# Vizualizacion matriz de confusion 

cm = confusion_matrix(y_held, y_pred_held)

plt.figure(figsize=(6, 5))
sb.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicción')
plt.ylabel('Valor real')
plt.title('Matriz de confusión')
plt.show()

